import Head from 'next/head';
import Banner from '../components/Banner';
import Header from '../components/Header';
import HomePost from '../components/HomePost';
import { sanityClient } from '../sanity';
import { Post } from '../typings';

interface HomeProps {
  posts: Post[];
}

export default function Home({ posts }: HomeProps) {
  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <HomePost posts={posts} />
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = `
    *[_type == 'post'] {
      _id,
      title,
      author -> {
        name,
        image
      },
      description,
      mainImage,
      slug
    }
  `;

  const posts = await sanityClient.fetch(query);
  return {
    props: {
      posts,
    }
  }
};
